name: presimal2022
dependencies:
  - python
  - pip
  - ipython
  - ipykernel
  - ipywidgets
  - jupyter
  - git
  - seaborn
  - conda-forge::jupyter_contrib_nbextensions
  - conda-forge::jupyterlab
  - pip:
    - pip
    - fastmonai
